### ISSUE TITLE
How can I get SMPL2d keypoints

### ISSUE THREAD

**Issue by dnqf11** [MartaYang/KITRO#1]
hello, thanks for your excting works. I just want to know how can I get this format keypoints to inference in the wild videos.

**Comment by MartaYang** [comment]
Hi, thank you for your interests and good question! Different from benchmark testing where ground truth 2D keypoints are typically used, in-the-wild videos can only have detected 2D keypoints. However, the format between 2D detectors and SMPL can differ significantly. Possible workarounds are (i) Train a detector directly in the SMPL format; or (ii) Learn a mapping from OpenPose to the SMPL format. More details and discussions on this can be found in Section G of our supplementary materials.

As discussed in our limitations and Sec. G of supp, KITRO can be sensitive to the 2D noise. Enhancing the robustness to 2D noise and providing full support for in-the-wild 2D detection are ongoing areas of future work.

**Comment by MartaYang** [comment]
As discussed in our limitations and Sec. G of supp, KITRO can be sensitive to the 2D noise. Enhancing the robustness to 2D noise and providing full support for in-the-wild 2D detection are ongoing areas of future work.
